spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://************
    password: ******
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none # 자동으로 테이블을 만들어줌 애플리케이션 실행시에 다 지우고 다시 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
cloud:
  aws:
    s3:
      bucket: bnksys
    credentials:
      access-key: *********
      secret-key: *********
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    org.hibernate:
      type:
        descriptor:
           sql: trace
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace # values(?,?)의 ?에 입력되는 로그를 남겨준다.
