spring:
  datasource:
    url: jdbc:mysql://database-2.cok0kgmbqg4l.us-east-1.rds.amazonaws.com:3306/fax?serverTimezone=Asia/Seoul
    username: admin
    password: gkfdkqjwl1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none # 자동으로 테이블을 만들어줌 애플리케이션 실행시에 다 지우고 다시 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always

server:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB
cloud:
  aws:
    s3:
      bucket: bnksys
    credentials:
      access-key: AKIAQWFGXVGCBCF4XLJA
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    org.hibernate:
      type:
        descriptor:
           sql: trace
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace # values(?,?)의 ?에 입력되는 로그를 남겨준다.